name: Docs

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Generate TypeDoc API docs
        run: pnpm exec typedoc --out docs/API packages

      - name: Ensure docs dir exists
        run: mkdir -p docs/WTs

      - name: Commit docs if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs README.md || true
          if git diff --cached --quiet; then
            echo "No documentation changes."
          else
            git commit -m "docs: update generated documentation"
            git push
          fi
