name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.4'
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '10.13.1'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Playwright Browsers
      run: pnpm test:e2e:install
    
    - name: Build application
      run: pnpm build
      env:
        # Mock Firebase config for build
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: test-project
        NEXT_PUBLIC_FIREBASE_API_KEY: test-api-key
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: test-project.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: test-project.appspot.com
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '123456789012'
        NEXT_PUBLIC_FIREBASE_APP_ID: '1:123456789012:web:test'
        FIREBASE_PROJECT_ID: test-project
        FIREBASE_CLIENT_EMAIL: firebase-adminsdk@test-project.iam.gserviceaccount.com
        FIREBASE_PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCtestkeymaterialonlyforunittests\nNOMORETHANTHIS\n-----END PRIVATE KEY-----\n'
        SESSION_COOKIE_NAME: __test_session
        NEXT_PUBLIC_APP_NAME: Fresh
    
    - name: Run E2E tests
      run: pnpm test:e2e
      env:
        CI: true
        # Test environment variables
        PLAYWRIGHT_BASE_URL: http://localhost:3000
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: test-project
        NEXT_PUBLIC_FIREBASE_API_KEY: test-api-key
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: test-project.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: test-project.appspot.com
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '123456789012'
        NEXT_PUBLIC_FIREBASE_APP_ID: '1:123456789012:web:test'
        SESSION_COOKIE_NAME: __test_session
        NEXT_PUBLIC_APP_NAME: Fresh
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30